services:
  - type: web
    name: ficore-mobile-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        value: 
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH

        value: /opt/render/project/src
